### ISSUE TITLE
No Module named ConfigParser

### ISSUE THREAD

**Issue by IntelligentFunction** [stb-tester/stbt-docker#18]
Is this going to be updated at some point as ConfigParser has been renamed to configparser if it hasn't been deprecated already.

**Comment by jcwork** [comment]
FYI, using python 3.6.8 on Windows, and as well as the error above, getting another failure for cStringIO... 

`Traceback (most recent call last):
  File "./stbt-docker", line 85, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

Traceback (most recent call last):
  File "./stbt-docker", line 98, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'`

**Comment by drothlis** [comment]
stbt-docker hasn't been ported to Python 3.

You can run Python 3 *inside the docker container*, but stbt-docker itself (the script that builds & launches the container) requires Python 2.
